### ISSUE TITLE
RGB-5050 led datasheet is wrong

### ISSUE THREAD

**Issue by xeniter** [badgeteam/mch2022-badge-hardware#88]
https://datasheet.lcsc.com/lcsc/1811131122_HONGLITRONIC-Hongli-Zhihui--HONGLITRONIC--HL-AF-5060H271BU46FU79GC-S1-THL_C219409.pdf

is wrong, also schematic, green and blue are swapped, at least with the led on my badge it is:

PIN 4 green and PIN 6 BLUE

**Comment by renzenicolai** [comment]
I'm not updating the hardware design as the names in the schematic match the LED in the bill of materials. We did give the sourcing agent some freedom when searching for the cheapest parts to use for production, that's why the LED colors are swapped: the datasheet is right, the schematic is right, it's just a different type of LED...

The documentation for the badge will be updated to reflect the actual LED colors.
